### ISSUE TITLE
Module1; Desktop Deployment Review

### ISSUE THREAD

**Issue by derrick1451** [mohametalmeari/mohametalmeari.github.io#11]
1. Kindly suggest you switch the div with the class header with a better HTML semantic tag eg the header tag for that case in order to make your project descriptive

**Comment by Bhekisile** [comment]
Your code looks presentable and clean, but what do you think about eliminating the div in your project and adding article tags and other semantic tags? It will make your code readable because semantic tags have meaning, unlike div tags.

**Comment by mohametalmeari** [comment]
Thank you for your comments
