### ISSUE TITLE
Peer to peer review - Mobile-menu

### ISSUE THREAD

**Issue by uno36** [mohametalmeari/mohametalmeari.github.io#14]
Good Job @mohametalmeari 👲

- correct use of GitHub flow
- all linter checks passed
- your code so far is working as required, finish the remaining code and you're good to go 👍
- keep up the good work
- kindly add the ESlint linter for your javascript👌
- may you please make sure the close button on your mobile menu is active 🧒

**Comment by mohametalmeari** [comment]
thanks
