### ISSUE TITLE
Pair to pair coding

### ISSUE THREAD

**Issue by Jonathan-kiprono** [mohametalmeari/mohametalmeari.github.io#8]
- Remove all comments in CSS file
- Include quotation in background Image with background image CSS property
-  In the Desktop Version, the cards should contain two columns unlike mobile version
- The preview photo in desktop version has to be in higher resolution

**Comment by Jonathan-kiprono** [comment]
- Remove all comments in CSS file
- Include quotation in background Image with background image CSS property
-  In the Desktop Version, the cards should contain two columns unlike mobile version
- The preview photo in desktop version has to be in higher resolution

**Comment by mohametalmeari** [comment]
Thank you for the comment, all done
